sudo: false

dist: trusty

language: node_js

node_js:
  - "7.10"
  - "8.2"

cache:
  directories:
    - node_modules

before_install:
  - "npm config set shrinkwrap false"
  - "test ! -d node_modules || npm prune"
  - "test ! -d node_modules || npm rebuild"

script:
  - "npm run-script test-travis"

after_script:
  - "test -d .nyc_output && npm install coveralls && nyc report --reporter=text-lcov | coveralls"